// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFMyYEpsy7LlsLnJPfbMyMLRmHX8tEQJ8',
    appId: '1:493726548222:ios:1994fd7861987826fee5af',
    messagingSenderId: '493726548222',
    projectId: 'end-project-d23ba',
    storageBucket: 'end-project-d23ba.firebasestorage.app',
    iosBundleId: 'com.example.endProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnqikjhGQSxpG-RVkmzNZswc1ZBOfQ9gI',
    appId: '1:493726548222:android:10d4f960e2c6927ffee5af',
    messagingSenderId: '493726548222',
    projectId: 'end-project-d23ba',
    storageBucket: 'end-project-d23ba.firebasestorage.app',
  );

}